### ISSUE TITLE
Audio device chose possibility greyed out after activate rigcrtl auto function

### ISSUE THREAD

**Issue by dominik0815** [DJ2LS/FreeDATA#407] opened 2023-05-04 16:53 UTC
Today I tried out new version of FreeData. My reported bug is now corrected and works fine with IC7300. But after startup and autoconnect rig the audio devvice chose field is empty. I tried to start modem, but also this does´nt work. It remains at the main window. After deactivate rig autoconnect and restart software all functions works very well.

![Bug Audio Device Greyed Out 04_05_2023](https://user-images.githubusercontent.com/64140671/236271853-04175e2d-a982-4a22-b5bc-c6b2395a0dbe.JPG)

**Comment by Mashintime** [comment] 2023-05-04 19:59
I'm not really sure what the issue is.  It works perfectly running from source.  I increased the timeout going that would help when running from app bundle but obviously not.  I'm really not sure how to get it working with the app bundle.

**Comment by DJ2LS** [comment] 2023-05-05 14:49
Problem might be, that 
a) daemon doesnt provide audio device information if the tnc ist started
b) TNC will be started too fast, so we might wait some mire time until audio devices are loaded
c) Wrong audio devices are selected and tnc can't be started.


@dominik0815 could you do me the favour, and starting the daemon manually? Just freedata-daemon.exe, in a separte command line terminal, then restarting the GUI and write as the console output?

**Comment by dominik0815** [comment] 2023-05-05 15:44
If FreeDATA-Daemon is started, all i working. Really, I tried without
dameon and bug is shown. If I try it with daemon all is working correctly
without bug. Really awesome.

Here the log from daemon:

2023-05-05T15:36:32.391397Z [info     ] [CFG] logfile init
file=config.ini
2023-05-05T15:36:32.392388Z [info     ] [DMN] Starting TCP/IP socket
port=3001
2023-05-05T15:36:32.394398Z [info     ] [DMN] Starting FreeDATA Daemon
author=DJ2LS version=0.9.0-alpha.2 year=2023
--- Logging error ---
2023-05-05T15:36:43.996655Z [debug    ] [SCK] Client connected
ip=127.0.0.1 port=59183
2023-05-05T15:36:46.153352Z [debug    ] [SCK] CMD
 command={'type': 'set', 'command': 'start_tnc', 'parameter': [{'mycall':
'DL1DJH-0', 'mygrid': 'JN47su', 'rx_audio': '8', 'tx_audio': '13',
'radiocontrol': 'rigctld', 'devicename': '3073', 'deviceport': 'COM5',
'pttprotocol': 'RIG', 'pttport': 'COM5', 'serialspeed': '115200',
'data_bits': '8', 'stop_bits': '1', 'handshake': 'None', 'rigctld_port':
'4532', 'rigctld_ip': '127.0.0.1', 'enable_scatter': 'True', 'enable_fft':
'True', 'enable_fsk': 'False', 'low_bandwidth_mode': 'False',
'tuning_range_fmin': '-50.0', 'tuning_range_fmax': '50.0',
'tx_audio_level': '95', 'respond_to_cq': 'True', 'rx_buffer_size': '16',
'enable_explorer': 'True', 'enable_stats': 'True', 'enable_auto_tune':
'False', 'tx_delay': '0'}]}
2023-05-05T15:36:46.154352Z [debug    ] [SCK] TNC Startup Config : mycall
value=DL1DJH-0
2023-05-05T15:36:46.155352Z [debug    ] [SCK] TNC Startup Config : mygrid
value=JN47su
2023-05-05T15:36:46.155352Z [debug    ] [SCK] TNC Startup Config : rx_audio
value=8
2023-05-05T15:36:46.156352Z [debug    ] [SCK] TNC Startup Config : tx_audio
value=13
2023-05-05T15:36:46.156352Z [debug    ] [SCK] TNC Startup Config :
radiocontrol value=rigctld
2023-05-05T15:36:46.156352Z [debug    ] [SCK] TNC Startup Config :
devicename value=3073
2023-05-05T15:36:46.157352Z [debug    ] [SCK] TNC Startup Config :
deviceport value=COM5
2023-05-05T15:36:46.157352Z [debug    ] [SCK] TNC Startup Config :
pttprotocol value=RIG
2023-05-05T15:36:46.157352Z [debug    ] [SCK] TNC Startup Config : pttport
value=COM5
2023-05-05T15:36:46.158352Z [debug    ] [SCK] TNC Startup Config :
serialspeed value=115200
2023-05-05T15:36:46.158352Z [debug    ] [SCK] TNC Startup Config :
data_bits value=8
2023-05-05T15:36:46.158352Z [debug    ] [SCK] TNC Startup Config :
stop_bits value=1
2023-05-05T15:36:46.159352Z [debug    ] [SCK] TNC Startup Config :
handshake value=None
2023-05-05T15:36:46.159352Z [debug    ] [SCK] TNC Startup Config :
rigctld_port value=4532
2023-05-05T15:36:46.159352Z [debug    ] [SCK] TNC Startup Config :
rigctld_ip value=127.0.0.1
2023-05-05T15:36:46.160353Z [debug    ] [SCK] TNC Startup Config :
enable_scatter value=True
2023-05-05T15:36:46.160353Z [debug    ] [SCK] TNC Startup Config :
enable_fft value=True
2023-05-05T15:36:46.160353Z [debug    ] [SCK] TNC Startup Config :
enable_fsk value=False
2023-05-05T15:36:46.161353Z [debug    ] [SCK] TNC Startup Config :
low_bandwidth_mode value=False
2023-05-05T15:36:46.162353Z [debug    ] [SCK] TNC Startup Config :
tuning_range_fmin value=-50.0
2023-05-05T15:36:46.162353Z [debug    ] [SCK] TNC Startup Config :
tuning_range_fmax value=50.0
2023-05-05T15:36:46.162353Z [debug    ] [SCK] TNC Startup Config :
tx_audio_level value=95
2023-05-05T15:36:46.163353Z [debug    ] [SCK] TNC Startup Config :
respond_to_cq value=True
2023-05-05T15:36:46.163353Z [debug    ] [SCK] TNC Startup Config :
rx_buffer_size value=16
2023-05-05T15:36:46.164354Z [debug    ] [SCK] TNC Startup Config :
enable_explorer value=True
2023-05-05T15:36:46.164354Z [debug    ] [SCK] TNC Startup Config :
enable_stats value=True
2023-05-05T15:36:46.165354Z [debug    ] [SCK] TNC Startup Config :
enable_auto_tune value=False
2023-05-05T15:36:46.169355Z [debug    ] [SCK] TNC Startup Config : tx_delay
value=0
['STARTTNC', 'DL1DJH-0', 'JN47su', '8', '13', 'rigctld', '127.0.0.1',
'4532', 'True', 'True', 'False', '-50.0', '50.0', 'False', '95', 'True',
'16', 'True', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], 'False', 'True', '0', None,
None, None, None, None, None, None, None, None, None, None, None, None,
None, None, None, None, None, None, None, None, None, None, None, None,
None, None, None, None, None, None, None, None, None, None, None, None,
None, None, None, None, None]
2023-05-05T15:36:46.170355Z [warning  ] [DMN] Starting TNC
port=127.0.0.1 rig=rigctld
2023-05-05T15:36:46.173356Z [info     ] [DMN] TNC started
 path=binary
2023-05-05 17:36:46 [info     ] [C2 ] Searching for libcodec2...
2023-05-05 17:36:46 [warning  ] [C2 ] Libcodec2 found but not loaded
e=PermissionError(13, 'Zugriff verweigert', None, 5, None)
path=libcodec2_ubuntu-20.04_Windows_i686-w64-mingw32.dll
2023-05-05 17:36:46 [warning  ] [C2 ] Libcodec2 found but not loaded
e=PermissionError(13, 'Zugriff verweigert', None, 5, None)
path=libcodec2_ubuntu-20.04_Windows_x86_64-w64-mingw32.dll
2023-05-05 17:36:46 [warning  ] [C2 ] Libcodec2 found but not loaded
e=OSError(8, '%1 ist keine zulässige Win32-Anwendung', None, 193, None)
path=libcodec2_ubuntu-20.04_Windows_i686-w64-mingw32.dll\libcodec2_Windows_i686-w64-mingw32.dll
2023-05-05 17:36:46 [info     ] [C2 ] Libcodec2 loaded
path=libcodec2_ubuntu-20.04_Windows_x86_64-w64-mingw32.dll\libcodec2_Windows_x86_64-w64-mingw32.dll
2023-05-05T15:36:47.674045Z [info     ] [TNC] Starting FreeDATA
 author=DJ2LS version=0.9.0-alpha.2
2023-05-05T15:36:47.677047Z [debug    ] [C2 ] Create 48<->8 kHz resampler
2023-05-05T15:36:47.678046Z [debug    ] [C2 ] Creating audio buffer
 size=9600
2023-05-05T15:36:47.679046Z [debug    ] [C2 ] Creating audio buffer
 size=9600
2023-05-05T15:36:47.680047Z [debug    ] [C2 ] Creating audio buffer
 size=9600
2023-05-05T15:36:47.680047Z [debug    ] [C2 ] Creating audio buffer
 size=9600
2023-05-05T15:36:47.681047Z [debug    ] [C2 ] Creating audio buffer
 size=9600
2023-05-05T15:36:47.682047Z [debug    ] [C2 ] Creating audio buffer
 size=9600
2023-05-05T15:36:47.683047Z [debug    ] [C2 ] Creating audio buffer
 size=9600
2023-05-05T15:36:47.730058Z [info     ] [MDM] init: opened audio devices
2023-05-05T15:36:47.730058Z [debug    ] [MDM] init: starting pyaudio
callback
2023-05-05T15:36:47.733059Z [info     ] [RIGCTLD] Connected DATA instance
to rigctld! ip=127.0.0.1 port=4532
2023-05-05T15:36:47.733059Z [info     ] [RIGCTLD] Connected PTT instance to
rigctld! ip=127.0.0.1 port=4532
2023-05-05T15:36:48.243534Z [debug    ] Rigctl DATA/PTT initialized
2023-05-05T15:36:48.246526Z [debug    ] [MDM] self.modem_transmit_queue
qsize=0
2023-05-05T15:36:48.246526Z [info     ] [EXPLORER] Publishing to
https://explorer.freedata.app state=True
2023-05-05T15:36:48.247535Z [info     ] [EXPLORER] publish
band=USB bandwidth=False callsign=DL1DJH-0 frequency=0 gridsquare=JN47su
version=0.9.0-alpha.2
2023-05-05T15:36:48.247535Z [info     ] [TNC] Starting TCP/IP socket
port=3000
2023-05-05T15:36:48.250537Z [debug    ] Starting new HTTPS connection (1):
api.freedata.app:443
2023-05-05T15:36:48.372958Z [debug    ] https://api.freedata.app:443 "POST
/explorer.php HTTP/1.1" 200 None
2023-05-05T15:36:48.542992Z [debug    ] [SCK] Client connected
ip=127.0.0.1 port=59205

Am Fr., 5. Mai 2023 um 16:49 Uhr schrieb DJ2LS ***@***.***>:

**Comment by Mashintime** [comment] 2023-05-25 03:38
May be fixed in #435

**Comment by Mashintime** [comment] 2023-07-12 20:23
Believe this has been fixed and no input from OP.

**Closed by Mashintime** 2023-07-12 20:23 UTC
Labels: bug
