### ISSUE TITLE
Pulse vanished with recent version 0.3.0.alpha1

### ISSUE THREAD

**Issue by frspin** [DJ2LS/FreeDATA#144] opened 2022-03-30 13:08 UTC
With recent changes Pulse device is vanished and there is no possibilities for a level adjustment in input.

Also, exiting from TNC, there is no exit from daemon:
`
15:04:22.135 (freedata-daemon)    › 2022-03-30 13:04:22 [warning  ] [DMN] Stopping TNC

15:04:22.924 (freedata-daemon)    › b'{"type":"set","command":"start_tnc","parameter":[{"mycall":"IW2DHW-","mygrid":"JN45op","rx_audio":"15","tx_audio":"15","radiocontrol":"rigctld","devicename":"RIG_MODEL_DUMMY_NOVFO","deviceport":"/dev/ttyS4","pttprotocol":"USB","pttport":"/dev/ttyS4","serialspeed":"9600","data_bits":"8","stop_bits":"1","handshake":"None","rigctld_port":"4532","rigctld_ip":"127.0.0.1","enable_scatter":"False","enable_fft":"True","low_bandwith_mode":"False","tuning_range_fmin":"-50.0","tuning_range_fmax":"50.0"}]}\n'
b'{"type" : "set", "command": "stop_tnc" , "parameter": "---" }\n'

15:04:35.440 (freedata-daemon)    › b''

15:04:35.581 (freedata-daemon)    › 2022-03-30 13:04:35 [warning  ] [SCK] Closing client socket    ip=127.0.0.1 port=34520
`

And, after this, only a Cntrl C can show 2 error message windows, a closing daemon message

15:05:58.407 (freedata-daemon)    › daemonProcess exited with code 0
 but a <return> is required for return to bash prompt

Regards
Franco Spinelli
IW2DHW

**Comment by DJ2LS** [comment] 2022-03-30 13:31
Hi @frspin , thanks for your feedback. Yes, there's a minor problem with the latest release. Because of my daytime job I didn't have the time yet to fix this. As soon as I fixed the audio problem we need to check if the problem still exists. 
The audio level adjustment is not yet implemented as there are many other areas where I need to work or still working at.  But it's on the todo list 👍

**Comment by DJ2LS** [comment] 2022-03-30 21:38
re pulse: Yes, this is because of a change of the audio library. Pulse support is in work, which can be tracked on the official PortAudio repository. The library I used before had some small support for pulse audio, but the library wasn't updated since 5 years, so I decided moving to a more updated one. Sorry, if this causes some problems for you, but the overall stability should increase in future time. I'm looking forward to native pulse support for PortAudio the next months 🤔

**Comment by frspin** [comment] 2022-03-31 06:50
Il 30/03/22 23:38, DJ2LS ha scritto:
> re pulse: Yes, this is because of a change of the audio library. Pulse 
> support is in work, which can be tracked on the official PortAudio 
> repository. The library I used before had some small support for pulse 
> audio, but the library wasn't updated since 5 years, so I decided moving 
> to a more updated one. Sorry, if this causes some problems for you, but 
> the overall stability should increase in future time. I'm looking 
> forward to native pulse support for PortAudio the next months 🤔

No problem for this.
Pulseaudio was a solution for level control in input and output.

Any other solution for this can be adopted.
I am unable to find a Portaudio mixer working as Pavucontrol in Pulseaudio.

Regards

Franco Spinelli
IW2DHW

**Comment by DJ2LS** [comment] 2022-03-31 07:03
Yes, I’m constantly looking for a solution which fits best for doing this.

**Comment by DJ2LS** [comment] 2022-03-31 07:31
This issue is now a duplicate of https://github.com/DJ2LS/FreeDATA/issues/117 , so I'd like to close this here. @frspin , would this be okay for you?

**Closed** 2022-04-03 15:19 UTC

**Comment by frspin** [comment] 2022-10-11 09:15
Il 31/03/22 09:31, DJ2LS ha scritto:
> This issue is now a duplicate of #117 
> <https://github.com/DJ2LS/FreeDATA/issues/117> , so I'd like to close 
> this here. @frspin <https://github.com/frspin> , would this be okay for you?

Not completely a duplicate.

Tune button is for transmit a constant carrier and adjust level of TX
Audio level slider(s) is for audio adjust.

In RX audio level adapt radio level to level required by program
In TX audio level is useful for adjust ALC radio
Both are required, as in WSJT-X which is using Pulse for input level 
adjust and a GUI slider for output level.

Regards

Franco Spinelli

**Comment by DJ2LS** [comment] 2022-10-11 09:20
Okay franco, could you open a new feature request for this?
Thanks
