### ISSUE TITLE
[Bug]: Frequency won't remain fixed when using VOX

### ISSUE THREAD

**Issue by danieldamon** [DJ2LS/FreeDATA#808] opened 2024-09-16 23:02 UTC
### FreeDATA Version

0.16.3-alpha

### What operating system are you using?

Other (specify below)

### Operating System Version

Linux and Windows

### Architecture

x64

### Area of problem

Server - General

### Describe the bug

When using VOX mode, the frequency should stay fixed after it is set. On Ubuntu version 0.16.3-alpha it stays momentarily then goes to NaN.  On Windows version 0.16.2-alpha, the same behavior can be seen

### To Reproduce

1. Set Rig control to VOX
2. use Frequency widget to set frequency at whatever is your choice.
3. Close widget and observe the frequency change back to unknown after a few seconds or minutes.

### Expected behavior

In order to report frequency on the FreeDATA explorer, the frequency must be known. So, in VOX mode, after being set by the frequency widget, it should remain fixed until changed.

**Comment by DJ2LS** [comment] 2024-09-17 06:24
Thanks for the feedback! 

Question is, could this be misleading, means, if a operator changes its frequency on the radio. So do we need an additional information somewhere which information,smithsonite the frequency is 8m this case just of informational character?

**Comment by danieldamon** [comment] 2024-09-17 15:51
smithonite?  Anyway, I'm pretty sure this is what other programs such as wstjx and varac to. For example, currently I'm in the middle of Arizona.  I'm having trouble with CAT, (not your problem), so I switched to VOX. But how can I indicate the frequency I'm running at if not manually inserted?

**Comment by danieldamon** [comment] 2024-09-17 15:52
(.. other programs do)

**Comment by danieldamon** [comment] 2024-09-17 16:00
Furthermore, the main reason I'm using VOX at the minute is because I don't have the USB to the transmitter isolated well enough.  In VOX, I'd expect communication to the transceiver to stop. However, I must unplug the USB to stop the noise from Freedata communication over the USB.

**Comment by DJ2LS** [comment] 2024-09-17 16:22
smithonite ... well, seems auto correction attacked me. I even don't know the meaning of this word. 

Okay, then it seems, it's making sense implementing this. Thanks for the feedback! 

What's the cause for the CAT problem? Any chance we can help?

**Comment by DJ2LS** [comment] 2024-09-17 17:24
Oh, I understand. I had this problem as well. However, let’s try to adjust the frequency thing.Thanks to your usb problems, the need for this adjustment is shown :-) Von meinem iPhone gesendetAm 17.09.2024 um 18:01 schrieb danlG ***@***.***>:﻿
Furthermore, the main reason I'm using VOX at the minute is because I don't have the USB to the transmitter isolated well enough.  In VOX, I'd expect communication to the transceiver to stop. However, I must unplug the USB to stop the noise from Freedata communication over the USB.

**Comment by danieldamon** [comment] 2024-09-17 17:56
I deleted the comment about noise over the USB when in VOX mode. My mistake - as I was in standard Rigcontrol mode. I think I need to put ferrite beads on my USB line to stop the noise. Like I said, I don't think it is a Freedata isssue.

**Comment by DJ2LS** [comment] 2024-09-18 18:03
pushed a commit, can be tested in develop branch, otherwise it will be part of the next release ( 0.16.4 )

**Comment by danieldamon** [comment] 2024-09-19 17:12
Confirmed that it works in the development branch for Linux

**Closed** 2024-09-21 13:38 UTC
Labels: bug :beetle:
