### ISSUE TITLE
Emoji/smiley/emoticon chooser in chat window can get stuck and will not close

### ISSUE THREAD

**Issue by g0hww** [DJ2LS/FreeDATA#338] opened 2023-01-22 17:43 UTC
**Describe the bug**
It is possible to get the smiley chooser stuck open in the chat dialog. Interaction with the chat dialog becomes awkward. It is possible, but not easy, to select another station from the list on the left. The main window is unaffected. CPU load is unaffected. Station seems to function normally.

**To Reproduce**
1. I did insert a smiley into a message I had written, but it didn't go where i wanted. I had set the character insertion point a few words back in the message. 
2. i tried to get out of the situation but couldn't make the smiley chooser close. 
3. now i have clicked on a different station and added smileys into a message i didn't want to write, to a station I didn't want to send a message to. 
4. closing and reopening the chat window doesn't help. 
5. The smiley chooser seems to be permanently stuck on the screen

**Desktop (please complete the following information):**
 - OS: Pop!_OS Linux
 - Version 22.04 LTS
 - Platform x86_64

**Additional context**
Perhaps hitting Esc could make the smiley chooser close, if there are no better ideas. I'm not a GUI expert so I don't know what is normal. Perhaps mouse clicking outside the chooser, too. Maybe closing the chat dialog.

I actually got out of the situation, by sending the message i didn't want to write, to the station I didn't want to send a message to, LOL.

![freedata-bug-smiley-chooser](https://user-images.githubusercontent.com/1413592/213931335-9c880947-36f2-4548-8095-4f443fdb6b3e.jpeg)

**Comment by DJ2LS** [comment] 2023-01-23 10:51
@Mashintime the chat needs some big improvements. As soon as we have reduced cpu load for the main gui, we need to adjust the chat

**Comment by Mashintime** [comment] 2023-01-23 23:57
Not able to reproduce, but if it happens again; does clicking the smiley icon (the one that opens the menu) also close the menu?

**Comment by DJ2LS** [comment] 2023-01-24 00:13
Yes, it does. But we need to add further close actions like we know from modern instant messengers. 
Maybe we should do some brainstorming,first

**Comment by DJ2LS** [comment] 2023-01-31 08:07
@g0hww can you test this? Just git pull from main.

When clicking on an emoji, the emoji window should close now.

**Comment by g0hww** [comment] 2023-02-01 18:42
I can now dismiss the smiley chooser by selecting a smiley. That seems to work.
However, once I have done that, and hit enter to transmit the message, it is not sent. The pending message is handled by the UI as if it was sent and moves up into the chat history.
I can then force it to be sent by clicking the little circular arrow to the left of the message in the chat history.
If i enter a message and insert no smiley characters, the message is sent immediately when i press Enter, as expected.
If I add a smiley into a message and then delete it, and press Enter, the message is sent immediately when i press Enter, as expected.
I have performed these actions many times and confirm that this is not a result of a busy channel or some other system state.

**Comment by DJ2LS** [comment] 2023-02-01 18:49
I can confirm this behaviour as I had it as well. @Mashintime we could close the emoticon chooser within „return listener“ as well and have a look there if this handler is getting called or not in this case

**Comment by Mashintime** [comment] 2023-02-02 00:03
Yes, was able to reproduce.  I believe it's related to the btoa function.  Investigating.

**Comment by DJ2LS** [comment] 2023-02-02 07:41
The btoa function is a critical area. Maybe we need some minor redesign of the chat part. But I’m not sure. At least simplifying it would help I think. But that’s a separate step with a huge amount of work I think

**Comment by Mashintime** [comment] 2023-02-02 11:35
The btoa function is throwing an error since the emoji is unicode(?--whatever char code it is is greater than a byte).  The resend doesn't use btoa so it works.  Still trying to come up with fix that works.

**Comment by DJ2LS** [comment] 2023-02-02 11:38
@Mashintime important side-node: When resending data, it will be processed

**Comment by Mashintime** [comment] 2023-02-02 11:41
@DJ2LS yes, that's the problem I'm running into, the receiving end isn't decoding the emojis correctly.

**Comment by DJ2LS** [comment] 2023-02-02 12:02
This would explain, why we had some lost messages in past.

**Comment by Mashintime** [comment] 2023-02-04 13:18
I was able to reproduce the window becoming stuck open, and now know why.  So I'll be reverting my attempted fix of closing the window after selecting an emoji.

**Closed** 2023-02-06 11:49 UTC
Labels: bug, enhancement, GUI
